const products = [
    {
        id: 1,
        image: "items images/item-1.webp",
        brand: "AASHIRVAAD",
        item_name: "AASHIRVAAD SHUDH CHAKKI WHOLE WHEAT",
        amount: 256,
        discount_amount: 219,
        discount: 14,
    },
    {
        id: 2,
        image: "items images/item-2.webp",
        brand: "SPENCER'S SMART CHOICE",
        item_name: "SMART CHOICE MAIDA 500G",
        amount: 58,
        discount_amount: 30,
        discount: 48,
    },
    {
        id: 3,
        image: "items images/item-3.webp",
        brand: "FORTUNE",
        item_name: "FORTUNE SOYA HEALTH REFINED SOYABEA",
        amount: 135,
        discount_amount: 111,
        discount: 15,
    },
    {
        id: 4,
        image: "items images/item-4.webp",
        brand: "FORTUNE",
        item_name: "FORTUNE PREMIUM KACHI GHANIPURE MU",
        amount: 96,
        discount_amount: 72,
        discount: 25,
    },
    {
        id: 5,
        image: "items images/item-5.jpeg",
        brand: "TATA",
        item_name: "TATA SALT",
        amount: 24,
        discount_amount: 20,
        discount: 4,
    },
    {
        id: 6,
        image: "items images/item-6.webp",
        brand: "FORTUNE",
        item_name: "FORTUNE SOYA HEALTH REFINED SOYABEA",
        amount: 135,
        discount_amount: 111,
        discount: 15,
    },
    {
        id: 7,
        image: "items images/item-7.jpg",
        brand: "FORTUNE",
        item_name: "FORTUNE SOYA HEALTH REFINED SOYABEA",
        amount: 135,
        discount_amount: 111,
        discount: 15,
    },
    {
        id: 8,
        image: "items images/item-8.webp",
        brand: "FORTUNE",
        item_name: "FORTUNE UNPOLISHED ARHAR DAL",
        amount: 135,
        discount_amount: 128,
        discount: 5,
    },
    {
        id: 9,
        image: "items images/item-9.webp",
        brand: "FORTUNE",
        item_name: "FORTUNE SOYA HEALTH REFINED SOYABEA",
        amount: 135,
        discount_amount: 111,
        discount: 15,
    },
    {
        id: 10,
        image: "items images/item-10.webp",
        brand: "FORTUNE",
        item_name: "FORTUNE SOYA HEALTH REFINED SOYABEA",
        amount: 135,
        discount_amount: 111,
        discount: 15,
    },
    {
        id: 11,
        image: "items images/item-11.webp",
        brand: "FORTUNE",
        item_name: "FORTUNE SOYA HEALTH REFINED SOYABEA",
        amount: 135,
        discount_amount: 111,
        discount: 15,
    },
    {
        id: 12,
        image: "items images/item-12.jpeg",
        brand: "FORTUNE",
        item_name: "FORTUNE SOYA HEALTH REFINED SOYABEA",
        amount: 135,
        discount_amount: 111,
        discount: 15,
    },
    {
        id: 13,
        image: "items images/item-13.webp",
        brand: "FORTUNE",
        item_name: "FORTUNE SOYA HEALTH REFINED SOYABEA",
        amount: 135,
        discount_amount: 111,
        discount: 15,
    },
    {
        id: 14,
        image: "items images/item-14.webp",
        brand: "FORTUNE",
        item_name: "FORTUNE SOYA HEALTH REFINED SOYABEA",
        amount: 135,
        discount_amount: 111,
        discount: 15,
    },
    {
        id: 15,
        image: "items images/item-15.webp",
        brand: "FORTUNE",
        item_name: "FORTUNE SOYA HEALTH REFINED SOYABEA",
        amount: 135,
        discount_amount: 111,
        discount: 15,
    },
    {
        id: 16,
        image: "items images/item-16.webp",
        brand: "FORTUNE",
        item_name: "FORTUNE SOYA HEALTH REFINED SOYABEA",
        amount: 135,
        discount_amount: 111,
        discount: 15,
    },
    {
        id: 17,
        image: "items images/item-17.webp",
        brand: "FORTUNE",
        item_name: "FORTUNE SOYA HEALTH REFINED SOYABEA",
        amount: 135,
        discount_amount: 111,
        discount: 15,
    },
    {
        id: 18,
        image: "items images/item-18.webp",
        brand: "FORTUNE",
        item_name: "FORTUNE SOYA HEALTH REFINED SOYABEA",
        amount: 135,
        discount_amount: 111,
        discount: 15,
    },
    {
        id: 19,
        image: "items images/item-19.webp",
        brand: "SPENCER'S SMART CHOICE",
        item_name: "SMART CHOICE ALMONDS WHOLE 1KG",
        amount: 770,
        discount_amount: 409,
        discount: 47,
    },
    {
        id: 20,
        image: "items images/item-20.webp",
        brand: "SPENCER'S SMART CHOICE",
        item_name: "SMART CHOICE CASHEW WHOLE 1KG",
        amount: 750,
        discount_amount: 430,
        discount: 38,
    },
    {
        id: 21,
        image: "items images/item-21.jpeg",
        brand: "FORTUNE",
        item_name: "FORTUNE SOYA HEALTH REFINED SOYABEA",
        amount: 135,
        discount_amount: 111,
        discount: 15,
    },
    {
        id: 22,
        image: "items images/item-22.jpeg",
        brand: "SPENCER'S SMART CHOICE",
        item_name: "SMART CHOICE CASHEW WHOLE 100G",
        amount: 160,
        discount_amount: 99,
        discount: 38,
    },
    {
        id: 23,
        image: "items images/item-23.webp",
        brand: "SPENCER'S SMART CHOICE",
        item_name: "SMART CHOICE ALMONDS WHOLE ",
        amount: 770,
        discount_amount: 409,
        discount: 47,
    },
    {
        id: 24,
        image: "items images/item-24.webp",
        brand: "FORTUNE",
        item_name: "FORTUNE SOYA HEALTH REFINED SOYABEA",
        amount: 135,
        discount_amount: 111,
        discount: 15,
    },
    {
        id: 25,
        image: "items images/item-25.webp",
        brand: "CADBARY",
        item_name: "FORTUNE SOYA HEALTH REFINED SOYABEA",
        amount: 135,
        discount_amount: 111,
        discount: 15,
    },
    {
        id: 26,
        image: "items images/item-26.webp",
        brand: "FORTUNE",
        item_name: "FORTUNE SOYA HEALTH REFINED SOYABEA",
        amount: 135,
        discount_amount: 111,
        discount: 15,
    },
    {
        id: 27,
        image: "items images/item-27.webp",
        brand: "FORTUNE",
        item_name: "FORTUNE SOYA HEALTH REFINED SOYABEA",
        amount: 135,
        discount_amount: 111,
        discount: 15,
    },
    {
        id: 28,
        image: "items images/item-28.webp",
        brand: "FORTUNE",
        item_name: "FORTUNE SOYA HEALTH REFINED SOYABEA",
        amount: 135,
        discount_amount: 111,
        discount: 15,
    },
    {
        id: 29,
        image: "items images/item-29.webp",
        brand: "FORTUNE",
        item_name: "FORTUNE SOYA HEALTH REFINED SOYABEA",
        amount: 135,
        discount_amount: 111,
        discount: 15,
    },
    {
        id: 30,
        image: "items images/item-30.webp",
        brand: "FORTUNE",
        item_name: "FORTUNE SOYA HEALTH REFINED SOYABEA",
        amount: 135,
        discount_amount: 111,
        discount: 15,
    },
];

export default products;